before_script:
  - docker info
  - '[ -d tmp ] || mkdir tmp'
  - git clone --single-branch --branch main https://github.com/OSC/ondemand-packaging.git $CI_PROJECT_DIR/tmp/ondemand-packaging
  - make rpm-packaging
  - make deb-packaging
stages:
  - build
  - deploy

variables:
  GIT_STRATEGY: clone
  OOD_BUILD_REPO: '2.1'
  OOD_PACKAGING_DEBUG: 'true'
  OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
  OOD_PACKAGING_GPG_PASSPHRASE: /systems/osc_certs/gpg/ondemand/.gpgpass

rpm-build:
  stage: build
  only:
    - tags
  script:
    - make rpm-packaging
    - make deb-packaging
    - ./tmp/ondemand-packaging/bin/ood_packaging -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output -V $CI_COMMIT_TAG -d $DIST $CI_PROJECT_DIR/packaging/rpm
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el7, el8, ubuntu-20.04]
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

deploy:
  stage: deploy
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /.*_.*/
  script:
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c main ./tmp/output/*
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c build -r $OOD_BUILD_REPO ./tmp/output/*
