before_script:
  - docker info
  - '[ -d tmp ] || mkdir tmp'
stages:
  - build
  - deploy

variables:
  GIT_STRATEGY: clone
  VERSION: v2.44.0
  OOD_BUILD_REPO: '4.1'
  OOD_PACKAGING_DEBUG: 'true'
  OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand-sha512.sec
  OOD_PACKAGING_GPG_PASSPHRASE: /systems/osc_certs/gpg/ondemand/.gpgpass

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH != "main" && $CI_COMMIT_TAG == null'
  script:
    - git clone --single-branch --branch main https://github.com/OSC/ondemand-packaging.git $CI_PROJECT_DIR/tmp/ondemand-packaging
    - ./tmp/ondemand-packaging/bin/ood_packaging -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output -V $VERSION -T $CI_PROJECT_DIR
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el8]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9]
        OOD_PACKAGING_ARCH: [x86_64, aarch64, ppc64le]
      - OOD_PACKAGING_DIST: [ubuntu-22.04, ubuntu-24.04, debian-12]
        OOD_PACKAGING_ARCH: [x86_64, aarch64]
      - OOD_PACKAGING_DIST: [amzn2023]
        OOD_PACKAGING_ARCH: [x86_64, aarch64]
  timeout: 5h
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$VERSION"

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - git clone --single-branch --branch main https://github.com/OSC/ondemand-packaging.git $CI_PROJECT_DIR/tmp/ondemand-packaging
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c main ./tmp/output/*
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c build -r $OOD_BUILD_REPO ./tmp/output/*
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c staging -r $OOD_BUILD_REPO ./tmp/output/*
