before_script:
  - docker info
  - '[ -d tmp ] || mkdir tmp'
stages:
  - build
  - deploy

variables:
  GIT_STRATEGY: clone
  OOD_BUILD_REPO: '3.1'
  OOD_PACKAGING_DEBUG: 'true'
  OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand-sha512.sec
  OOD_PACKAGING_GPG_PASSPHRASE: /systems/osc_certs/gpg/ondemand/.gpgpass

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - git clone --single-branch --branch main https://github.com/OSC/ondemand-packaging.git $CI_PROJECT_DIR/tmp/ondemand-packaging
    - ./tmp/ondemand-packaging/bin/ood_packaging -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output -V $CI_COMMIT_TAG -T $CI_PROJECT_DIR
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el7, el8]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9, amzn2023, ubuntu-20.04, ubuntu-22.04]
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

build-3.0:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - git clone --single-branch --branch 3.0 https://github.com/OSC/ondemand-packaging.git $CI_PROJECT_DIR/tmp/ondemand-packaging
    - ./tmp/ondemand-packaging/bin/ood_packaging -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output-3.0 -V $CI_COMMIT_TAG -T $CI_PROJECT_DIR
  parallel:
    matrix:
      - OOD_PACKAGING_DIST: [el7, el8]
        OOD_PACKAGING_GPG_PRIVATE_KEY: /systems/osc_certs/gpg/ondemand/ondemand.sec
      - OOD_PACKAGING_DIST: [el9, ubuntu-20.04, ubuntu-22.04]
  artifacts:
    paths:
      - tmp/output-3.0
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - git clone --single-branch --branch main https://github.com/OSC/ondemand-packaging.git $CI_PROJECT_DIR/tmp/ondemand-packaging
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c main ./tmp/output/*
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c build -r $OOD_BUILD_REPO ./tmp/output/*

deploy-3.0:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - git clone --single-branch --branch 3.0 https://github.com/OSC/ondemand-packaging.git $CI_PROJECT_DIR/tmp/ondemand-packaging
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c main ./tmp/output-3.0/*
    - ./tmp/ondemand-packaging/release.py --debug --pkey /systems/osc_certs/ssh/ondemand-packaging/id_rsa -c build -r 3.0 ./tmp/output-3.0/*
