name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dist: ["el7", "el8", "ubuntu-20.04", "ubuntu-22.04"]
        version: ["v2.31.1"]
    runs-on: "ubuntu-latest"
    name: Build test ${{ matrix.version }} for ${{ matrix.dist }}

    steps:
      - name: Checkout ${{ github.sha	}}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get ondemand-packaging
        run: |
          mkdir -p tmp
          git clone --single-branch --branch main https://github.com/OSC/ondemand-packaging.git tmp/ondemand-packaging

      - name: Build package
        run: |
          ./tmp/ondemand-packaging/bin/ood_packaging -w $(pwd)/tmp/work -o $(pwd)/tmp/output -V ${{ matrix.version }} -T $(pwd)
        env:
          OOD_PACKAGING_DIST: ${{ matrix.dist }}
          OOD_PACKAGING_DEBUG: 'true'
